//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagMonkey.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lyricwiki.org/server.php")]
        public string LyricWikiUrl {
            get {
                return ((string)(this["LyricWikiUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div class=\\\'lyricbox\\\'><div class=\'rtMatcher\'>.*</div>(?<LYRICS>.*)<!--")]
        public string LyricWikiParserRegex {
            get {
                return ((string)(this["LyricWikiParserRegex"]));
            }
            set {
                this["LyricWikiParserRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a65154a4c8dadfea92f93c0a7c94492f")]
        public string LastfmApiKey {
            get {
                return ((string)(this["LastfmApiKey"]));
            }
            set {
                this["LastfmApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10c98fc8a17e17085c8c24d54fa7c304")]
        public string LastfmApiSecret {
            get {
                return ((string)(this["LastfmApiSecret"]));
            }
            set {
                this["LastfmApiSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lyrics.wikia.com/")]
        public string MediaWikiApiBaseUrl {
            get {
                return ((string)(this["MediaWikiApiBaseUrl"]));
            }
            set {
                this["MediaWikiApiBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Category:Instrumental")]
        public string MediaWikiInstrumentalCategory {
            get {
                return ((string)(this["MediaWikiInstrumentalCategory"]));
            }
            set {
                this["MediaWikiInstrumentalCategory"] = value;
            }
        }
    }
}
