//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagMonkey.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lyricwiki.org/server.php")]
        public string LyricWikiUrl {
            get {
                return ((string)(this["LyricWikiUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a65154a4c8dadfea92f93c0a7c94492f")]
        public string LastfmApiKey {
            get {
                return ((string)(this["LastfmApiKey"]));
            }
            set {
                this["LastfmApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10c98fc8a17e17085c8c24d54fa7c304")]
        public string LastfmApiSecret {
            get {
                return ((string)(this["LastfmApiSecret"]));
            }
            set {
                this["LastfmApiSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{{Instrumental}}")]
        public string MediaWikiInstrumentalTemplate {
            get {
                return ((string)(this["MediaWikiInstrumentalTemplate"]));
            }
            set {
                this["MediaWikiInstrumentalTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lyrics.wikia.com/api.php?action=query&prop=revisions&titles={0}&rvprop=tim" +
            "estamp|user|comment|content&format=xml")]
        public string MediaWikiApiGetLyricsUrl {
            get {
                return ((string)(this["MediaWikiApiGetLyricsUrl"]));
            }
            set {
                this["MediaWikiApiGetLyricsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lyrics.wikia.com/api.php?action=query&list=search&format=xml&srsearch={0}")]
        public string MediaWikiApiSearchUrl {
            get {
                return ((string)(this["MediaWikiApiSearchUrl"]));
            }
            set {
                this["MediaWikiApiSearchUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\<lyrics\\>(?<LYRICS>.*)\\<\\/lyrics\\>")]
        public string LyricWikiParserRegex {
            get {
                return ((string)(this["LyricWikiParserRegex"]));
            }
            set {
                this["LyricWikiParserRegex"] = value;
            }
        }
    }
}
